# Level 12: Cleaning Sample Metadata

In this notebook you will load sample metadata and deal with missing values.

Metadata describes samples. In bioinformatics, metadata can include tissue type, disease status, age, sequencing depth, and other information.

In [1]:
import pandas as pd

## 1. Load the metadata CSV

In [2]:
metadata = pd.read_csv("data/sample_metadata.csv")
metadata

  sample_id patient_id  tissue condition   age  sequencing_depth
0       S01       P001   blood   control  34.0        12000000.0
1       S02       P002   blood   disease  45.0        15000000.0
2       S03       P003  tumour   disease  52.0        22000000.0
3       S04       P004  tumour   disease   NaN        21000000.0
4       S05       P005   blood   control  29.0               NaN
5       S06       P006  tumour   disease  61.0        25000000.0
6       S07       P007   blood   control  38.0        13000000.0
7       S08       P008  tumour   disease  55.0        24000000.0

## 2. Check for missing values

`isna()` checks whether a value is missing. `sum()` counts how many missing values are in each column.

In [3]:
metadata.isna().sum()

sample_id           0
patient_id          0
tissue              0
condition           0
age                 1
sequencing_depth    1
dtype: int64

## 3. Fill missing numeric values

For this exercise, we will fill missing `age` and `sequencing_depth` values using the column median.

In [4]:
metadata["age"] = metadata["age"].fillna(metadata["age"].median())
metadata["sequencing_depth"] = metadata["sequencing_depth"].fillna(metadata["sequencing_depth"].median())
metadata

  sample_id patient_id  tissue condition   age  sequencing_depth
0       S01       P001   blood   control  34.0        12000000.0
1       S02       P002   blood   disease  45.0        15000000.0
2       S03       P003  tumour   disease  52.0        22000000.0
3       S04       P004  tumour   disease  45.0        21000000.0
4       S05       P005   blood   control  29.0        21000000.0
5       S06       P006  tumour   disease  61.0        25000000.0
6       S07       P007   blood   control  38.0        13000000.0
7       S08       P008  tumour   disease  55.0        24000000.0

## 4. Count samples by condition

`value_counts()` counts how many times each value appears.

In [5]:
metadata["condition"].value_counts()

condition
disease    5
control    3
Name: count, dtype: int64

## 5. Save the cleaned table

`to_csv()` writes a DataFrame to a new CSV file. `index=False` prevents pandas from adding an extra row number column.

In [6]:
metadata.to_csv("data/sample_metadata_cleaned.csv", index=False)

## Practice tasks

1. Count how many samples come from each `tissue`.
2. Calculate the average age for each `condition`.
3. Select only the disease samples.
4. Save the disease samples to a new file called `disease_samples.csv`.

In [ ]:
# Write your answers here