# Level 11: Loading Gene Expression CSV Data

In this notebook you will learn how to load a CSV file using `pandas`.

The data contains expression values for several genes across three samples.

## 1. Import pandas

`pandas` is a Python library for working with tables.

In [1]:
import pandas as pd

## 2. Load the CSV file

`read_csv()` reads a CSV file and stores it as a table called a DataFrame.

In [2]:
expression = pd.read_csv("data/gene_expression.csv")
expression

           gene_id gene_name  sample_A  sample_B  sample_C
0  ENSG00000141510      TP53       120       135        98
1  ENSG00000171862      PTEN        45        50        42
2  ENSG00000139618     BRCA2        88        76        91
3  ENSG00000012048     BRCA1       102       110        99
4  ENSG00000157764      BRAF        60        80        75
5  ENSG00000146648      EGFR       200       180       210
6  ENSG00000136997       MYC       150       170       160
7  ENSG00000134086       VHL        30        28        35

## 3. Inspect the data

These commands help you understand the table before doing any analysis.

In [3]:
expression.head()

           gene_id gene_name  sample_A  sample_B  sample_C
0  ENSG00000141510      TP53       120       135        98
1  ENSG00000171862      PTEN        45        50        42
2  ENSG00000139618     BRCA2        88        76        91
3  ENSG00000012048     BRCA1       102       110        99
4  ENSG00000157764      BRAF        60        80        75

In [4]:
expression.shape

(8, 5)

In [5]:
expression.columns

Index(['gene_id', 'gene_name', 'sample_A', 'sample_B', 'sample_C'], dtype='object')

## 4. Select columns

Use square brackets to select one column from the table.

In [6]:
expression["gene_name"]

0     TP53
1     PTEN
2    BRCA2
3    BRCA1
4     BRAF
5     EGFR
6      MYC
7      VHL
Name: gene_name, dtype: object

## 5. Calculate the average expression

Here we calculate the mean expression for each gene across the three samples.

In [7]:
expression["mean_expression"] = expression[["sample_A", "sample_B", "sample_C"]].mean(axis=1)
expression

           gene_id gene_name  sample_A  sample_B  sample_C  mean_expression
0  ENSG00000141510      TP53       120       135        98       117.666667
1  ENSG00000171862      PTEN        45        50        42        45.666667
2  ENSG00000139618     BRCA2        88        76        91        85.000000
3  ENSG00000012048     BRCA1       102       110        99       103.666667
4  ENSG00000157764      BRAF        60        80        75        71.666667
5  ENSG00000146648      EGFR       200       180       210       196.666667
6  ENSG00000136997       MYC       150       170       160       160.000000
7  ENSG00000134086       VHL        30        28        35        31.000000

## Practice tasks

1. Display only the `gene_name` and `sample_A` columns.
2. Find the gene with the highest `mean_expression`.
3. Find the gene with the lowest `mean_expression`.
4. Add a new column called `range_expression` equal to the maximum sample value minus the minimum sample value.

In [ ]:
# Write your answers here