# Level 13: Filtering Genomic Variants

In this notebook you will filter a variant table.

Variant tables often contain many rows. Bioinformaticians usually apply filters to focus on variants with enough evidence or higher predicted impact.

In [1]:
import pandas as pd

## 1. Load the variants CSV

In [2]:
variants = pd.read_csv("data/variants.csv")
variants

,chromosome,position,gene,variant_type,impact,read_depth,allele_frequency
0,17,7674220,TP53,SNV,HIGH,80,0.42
1,10,87933125,PTEN,DEL,HIGH,65,0.35
2,13,32316461,BRCA2,SNV,MODERATE,40,0.18
3,7,140453136,BRAF,SNV,HIGH,120,0.51
4,7,55249071,EGFR,INS,MODERATE,30,0.09
5,8,128748315,MYC,SNV,LOW,22,0.05
6,3,10183767,VHL,DEL,HIGH,55,0.28
7,17,43044295,BRCA1,SNV,MODERATE,75,0.22

## 2. Filter by read depth

Read depth is the number of sequencing reads supporting a genomic position. Higher depth usually gives more confidence.

In [3]:
high_depth = variants[variants["read_depth"] >= 50]
high_depth

,chromosome,position,gene,variant_type,impact,read_depth,allele_frequency
0,17,7674220,TP53,SNV,HIGH,80,0.42
1,10,87933125,PTEN,DEL,HIGH,65,0.35
3,7,140453136,BRAF,SNV,HIGH,120,0.51
6,3,10183767,VHL,DEL,HIGH,55,0.28
7,17,43044295,BRCA1,SNV,MODERATE,75,0.22

## 3. Filter by predicted impact

In [4]:
high_impact = variants[variants["impact"] == "HIGH"]
high_impact

,chromosome,position,gene,variant_type,impact,read_depth,allele_frequency
0,17,7674220,TP53,SNV,HIGH,80,0.42
1,10,87933125,PTEN,DEL,HIGH,65,0.35
3,7,140453136,BRAF,SNV,HIGH,120,0.51
6,3,10183767,VHL,DEL,HIGH,55,0.28

## 4. Combine filters

Use `&` for AND. Each condition must be inside parentheses.

In [5]:
important_variants = variants[(variants["read_depth"] >= 50) & (variants["impact"] == "HIGH")]
important_variants

,chromosome,position,gene,variant_type,impact,read_depth,allele_frequency
0,17,7674220,TP53,SNV,HIGH,80,0.42
1,10,87933125,PTEN,DEL,HIGH,65,0.35
3,7,140453136,BRAF,SNV,HIGH,120,0.51
6,3,10183767,VHL,DEL,HIGH,55,0.28

## 5. Sort variants

Sorting helps you see the largest or smallest values first.

In [6]:
variants.sort_values("allele_frequency", ascending=False)

,chromosome,position,gene,variant_type,impact,read_depth,allele_frequency
3,7,140453136,BRAF,SNV,HIGH,120,0.51
0,17,7674220,TP53,SNV,HIGH,80,0.42
1,10,87933125,PTEN,DEL,HIGH,65,0.35
6,3,10183767,VHL,DEL,HIGH,55,0.28
7,17,43044295,BRCA1,SNV,MODERATE,75,0.22
2,13,32316461,BRCA2,SNV,MODERATE,40,0.18
4,7,55249071,EGFR,INS,MODERATE,30,0.09
5,8,128748315,MYC,SNV,LOW,22,0.05

## Practice tasks

1. Select variants with `allele_frequency` greater than or equal to 0.20.
2. Select only variants in the `TP53`, `BRCA1`, or `BRCA2` genes.
3. Count how many variants there are for each `variant_type`.
4. Save the `important_variants` table to `data/important_variants.csv`.

In [7]:
# Write your answers here